[package]
name = "jucombinator"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "jucombinator"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
itertools = "0.11.0"
